# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'headout' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

# UI
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
# Networking
#  pod 'AFNetworking'
#  pod 'SwiftyJSON'
#  pod 'Alamofire'
#  pod 'ObjectMapper'

# Utilities
#  pod 'Kingfisher'
#  pod 'RxSwift'
#  pod 'RxCocoa'

# Video
  pod 'Player'
  pod 'YouTubePlayer'

  # Pods for headout

  target 'headoutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'headoutUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
